version: "3"
services:
  api:
    container_name: expense_api
    #-it flag (for older versions of react)
    stdin_open: true
    tty: true

    #Build from current directory
    build:
      context: ./app/api
      dockerfile: Dockerfile
      
    #ports
    ports:
      - "8000:8000"

    #Bind mount
    volumes:
      - "./app/api:/api"
    
    #Environment variables
    env_file:
      - "./app/api/.env.prod"
  
  web:
    container_name: expense_prod_ui
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.prod

    ports:
      - "4000:4000"
    env_file:
      - "./app/frontend/.env"

    environment:
      NODE_ENV: production
    depends_on:
      - api